version: '2'
services:
  dev:
    build: .
    command: python3 manage.py migrate
    command: python3 manage.py collectstatic --noinput
    command: python3 manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db