version: 2
jobs:
  build:
    working_directory: ~/odelife
    docker:
      - image: python:3.6.0
      - image: postgres:9.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: odelifedb1
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: tr1
