# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aroma', '0016_auto_20170602_1844'),
        ('accounts', '0002_auto_20170615_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='collection',
            field=models.ManyToManyField(blank=True, related_name='collection', to='aroma.Aroma'),
        ),
        migrations.AddField(
            model_name='account',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='aroma.Aroma'),
        ),
    ]
