# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aroma', '0017_aroma_slug'),
        ('tag', '0002_auto_20170622_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
        migrations.AddField(
            model_name='tag',
            name='aroma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aroma.Aroma'),
        ),
    ]
