# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aroma', '0018_auto_20170711_1722'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('tag', '0003_auto_20170711_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('aroma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aroma.Aroma')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.RemoveField(
            model_name='tag',
            name='aroma',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='color_hex',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='object_id',
        ),
        migrations.AddField(
            model_name='taggeditem',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tag.Tag'),
        ),
    ]
