# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-19 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('parent_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
