# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-20 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aroma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aroma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('pic', models.URLField(blank=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[(b'f', b'female'), (b'm', b'male'), (b'u', b'unisex')], default='u', max_length=1)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True)),
                ('logo', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nose',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('biography', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('pic', models.URLField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='aroma',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aroma.Brand'),
        ),
        migrations.AddField(
            model_name='aroma',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aroma.Group'),
        ),
        migrations.AddField(
            model_name='aroma',
            name='noses',
            field=models.ManyToManyField(to='aroma.Nose'),
        ),
        migrations.AddField(
            model_name='aroma',
            name='notes',
            field=models.ManyToManyField(to='aroma.Note'),
        ),
    ]
