# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-20 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aroma', '0005_auto_20170420_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aroma',
            name='noses',
            field=models.ManyToManyField(blank=True, null=True, to='aroma.Nose'),
        ),
    ]
