# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-03 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aroma', '0007_auto_20170502_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='AromaCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_comments', models.IntegerField(blank=True, null=True)),
                ('num_views', models.IntegerField(blank=True, null=True)),
                ('aroma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aroma.Aroma')),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='group',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aroma.Group'),
        ),
    ]
