# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-03 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aroma', '0008_auto_20170503_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aroma',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='aroma',
            unique_together=set([('title', 'brand')]),
        ),
    ]
