# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-03 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aroma', '0009_auto_20170503_2108'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aroma',
            unique_together=set([('title', 'brand', 'gender')]),
        ),
    ]
