# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-04 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aroma', '0011_auto_20170504_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='aroma',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
