# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-06 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aroma', '0012_aroma_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aroma',
            name='gender',
            field=models.CharField(choices=[('f', 'женский'), ('m', 'мужской'), ('u', 'унисекс')], default='u', max_length=1),
        ),
    ]
