# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-15 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aroma', '0013_auto_20170506_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.SmallIntegerField(choices=[(0, 'top_notes'), (1, 'middle_notes'), (2, 'base_notes'), (3, 'general_notes')])),
            ],
        ),
        migrations.RemoveField(
            model_name='aroma',
            name='base_notes',
        ),
        migrations.RemoveField(
            model_name='aroma',
            name='middle_notes',
        ),
        migrations.RemoveField(
            model_name='aroma',
            name='top_notes',
        ),
        migrations.RemoveField(
            model_name='aroma',
            name='notes',
        ),
        migrations.AddField(
            model_name='aroma',
            name='notes',
            field=models.ManyToManyField(blank=True, related_name='notes', through='aroma.CategoryNotes', to='aroma.Note'),
        ),
        migrations.AddField(
            model_name='categorynotes',
            name='aroma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aroma.Aroma'),
        ),
        migrations.AddField(
            model_name='categorynotes',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aroma.Note'),
        ),
    ]
