# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-02 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aroma', '0014_auto_20170515_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='aroma',
            name='group',
        ),
        migrations.AddField(
            model_name='aroma',
            name='group',
            field=models.ManyToManyField(blank=True, to='aroma.Group'),
        ),
        migrations.AddField(
            model_name='aroma',
            name='guise',
            field=models.ImageField(blank=True, null=True, upload_to='guises/'),
        ),

    ]
