# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aroma', '0017_aroma_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorynotes',
            name='category',
            field=models.SmallIntegerField(choices=[(0, 'top_notes'), (1, 'middle_notes'), (2, 'base_notes'), (3, 'general_notes')], default=3),
        ),
    ]
