# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aroma', '0018_auto_20170711_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aroma',
            options={'ordering': ('title',)},
        ),
        migrations.AddField(
            model_name='aroma',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='aroma',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='aroma',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
