# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aroma', '0019_auto_20170801_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='aroma',
            name='ru_trans',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='ru_trans',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
