# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 14:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aroma', '0017_aroma_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('F', 'Favorite'), ('L', 'Like'), ('U', 'Up Vote'), ('D', 'Down Vote')], max_length=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('text', models.TextField()),
                ('longevity', models.CharField(choices=[('M', 'Средняя'), ('W', 'Слабая'), ('S', 'Сильная')], max_length=1)),
                ('sillage', models.CharField(choices=[('M', 'Средний'), ('W', 'Близко к коже'), ('S', 'Сильный')], max_length=1)),
                ('season', models.CharField(choices=[('SP', 'Весна'), ('SM', 'Лето'), ('A', 'Осень'), ('W', 'Зима'), ('E', 'Любое')], max_length=2)),
                ('impression', models.CharField(choices=[('F', 'Люблю'), ('L', 'Нравится'), ('N', 'Нейтрально'), ('D', 'Не нравится')], max_length=1)),
                ('rating', models.SmallIntegerField(default=0)),
                ('aroma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aroma.Aroma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
