# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20170619_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='impression',
            field=models.CharField(choices=[('F', 'Люблю'), ('L', 'Нравится'), ('N', 'Нейтральное'), ('D', 'Не нравится')], max_length=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='longevity',
            field=models.CharField(blank=True, choices=[('S', 'Сильная'), ('M', 'Средняя'), ('W', 'Слабая')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='season',
            field=models.CharField(blank=True, choices=[('SP', 'Весна'), ('SM', 'Лето'), ('A', 'Осень'), ('W', 'Зима'), ('E', 'Любой')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='sillage',
            field=models.CharField(blank=True, choices=[('S', 'Сильный'), ('M', 'Средний'), ('W', 'Близко к коже')], max_length=1, null=True),
        ),
    ]
